spring:
  application:
    name: ocp-demo-1
server:
  port: 9001

management:
  endpoints:
    prometheus:
      enabled: true
    health:
      show-details: always
    web:
      exposure:
        include: "*"
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db


