apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kamalredhat-2025-dev
  name: 'ocp-swagger-demo-deployment'
spec:
  selector:
    matchLabels:
      app: ocp-swagger-demo-deployment
  replicas: 3
  template:
    metadata:
      labels:
        app: ocp-swagger-demo-deployment
    spec:
      containers:
        - name: ocp-swagger-demo-deployment
          image: >-
            docker.io/kamaltechlearn/ocp-swagger-demo:3.0
          ports:
            - containerPort: 9001
              protocol: TCP
          env:
            # ConfigMap values
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: ocp-swagger-demo-config
                  key: APP_NAME

            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: ocp-swagger-demo-config
                  key: SERVER_PORT

            - name: SWAGGER_API_DOCS_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: ocp-swagger-demo-config
                  key: SWAGGER_API_DOCS_ENABLED

            - name: SWAGGER_UI_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: ocp-swagger-demo-config
                  key: SWAGGER_UI_ENABLED

            - name: SWAGGER_UI_PATH
              valueFrom:
                configMapKeyRef:
                  name: ocp-swagger-demo-config
                  key: SWAGGER_UI_PATH

            - name: SWAGGER_DISPLAY_DURATION
              valueFrom:
                configMapKeyRef:
                  name: ocp-swagger-demo-config
                  key: SWAGGER_DISPLAY_DURATION

            - name: SWAGGER_TRY_OUT
              valueFrom:
                configMapKeyRef:
                  name: ocp-swagger-demo-config
                  key: SWAGGER_TRY_OUT

            - name: SWAGGER_OPERATION_SORTER
              valueFrom:
                configMapKeyRef:
                  name: ocp-swagger-demo-config
                  key: SWAGGER_OPERATION_SORTER

            - name: SWAGGER_TAG_SORTER
              valueFrom:
                configMapKeyRef:
                  name: ocp-swagger-demo-config
                  key: SWAGGER_TAG_SORTER

            # Secret values

            - name: MY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ocp-swagger-demo-secret
                  key: MY_USERNAME

            - name: MY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ocp-swagger-demo-secret
                  key: MY_PASSWORD
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
