spring:
  application:
    name: openshift-demo

server:
  port: 9001


springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    display-request-duration: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
