apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kamalredhat-2025-dev
  name: 'ocp-swagger-demo-deployment'
spec:
  selector:
    matchLabels:
      app: ocp-swagger-demo-deployment
  replicas: 3
  template:
    metadata:
      labels:
        app: ocp-swagger-demo-deployment
    spec:
      containers:
        - name: ocp-swagger-demo-deployment
          image: >-
            docker.io/kamaltechlearn/ocp-swagger-env-demo:1.0
          ports:
            - containerPort: 9001
              protocol: TCP
          env:
            # ConfigMap values
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: ocp-swagger-demo-config
                  key: SERVER_PORT
            - name: SWAGGER_UI_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: ocp-swagger-demo-config
                  key: SWAGGER_UI_ENABLED
            # Secret values
            - name: MY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ocp-swagger-demo-secret
                  key: MY_USERNAME
            - name: MY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ocp-swagger-demo-secret
                  key: MY_PASSWORD
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
