apiVersion: v1
kind: Service
metadata:
  name: ocp-swagger-demo-service
  namespace: kamalredhat-2025-dev
spec:
  selector:
    app: ocp-swagger-demo-deployment
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001