plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.1'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.skh'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	implementation 'org.springdoc:springdoc-openapi-starter-webflux-ui:3.1.0'
	runtimeOnly 'com.mysql:mysql-connector-j'
	testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webflux-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	annotationProcessor 'org.projectlombok:lombok'
	testCompileOnly 'org.projectlombok:lombok'

	// JJWT API - Core library
	implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
	// JJWT Implementation - Runtime only
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
	// JJWT Jackson - For JSON processing (runtime only)
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
//
//	// JWT
//	implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
//	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
//	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'


//	implementation 'org.springframework.security:spring-security-crypto'


}

/*
tasks.named('test') {
	useJUnitPlatform()
}
*/
